### ISSUE TITLE
 multiply by 2 when calculating floating-point operations?

### ISSUE THREAD

**Issue by lxy5513** [ZZZHANG-jx/DocRes#10]
from thop import profile 
    input = torch.rand((1, 6, 256, 256))
    gflops,params = profile(model,inputs=(input,))
    **gflops = gflops*2 / 10**9**
    params = params / 10**6
    print(gflops,'==============')
    print(params,'==============')
    

     Hello, why do we need to multiply by 2 when calculating floating-point operations? @ZZZHANG-jx

**Comment by ZZZHANG-jx** [comment]
The profile function in the thop library only considers the number of multiplications. If you also account for addition operations, the final FLOPs are approximately twice the result. For more details, you can refer to this [link](https://github.com/Lyken17/pytorch-OpCounter/tree/master/benchmark#macs-flops-what-is-the-difference).

**Comment by lxy5513** [comment]
@ZZZHANG-jx I get it, thanks for u kind replay
