### ISSUE TITLE
Question for training the model

### ISSUE THREAD

**Issue by LonglongaaaGo** [ZZZHANG-jx/DocRes#11]
Hi @ZZZHANG-jx ,

Thank you so much for your awesome paper and project.
I have a question about the model training.
If we would like to train another new dataset.
Should we train the two models separately, or just training one model is ok, as mentioned in the paper?
For example, for the deblur task?
Thanks!

**Comment by ZZZHANG-jx** [comment]
For different tasks/datasets, we only train one model, not multiple models. If you want to add more tasks/datasets, you just need to train these new data together with the original data. Of course, you need to design an appropriate DTSPrompt to distinguish the tasks. One simple way is to specify a constant (fixed prompt) as the prompt, as we demonstrated in the ablation study in Table 2 of the paper.

**Comment by LonglongaaaGo** [comment]
Awesome！ Thanks!
