### ISSUE TITLE
about inference size

### ISSUE THREAD

**Issue by zhaozhaoooo** [ZZZHANG-jx/DocRes#15]
hello! very nice work！ but i have a question about inference size.
when the model is trained, the image is cropped to 256*256, but when inference, the image is expanded to multiples of eight. 
Does the model fail in this way?

**Comment by ZZZHANG-jx** [comment]
> hello! very nice work！ but i have a question about inference size. when the model is trained, the image is cropped to 256*256, but when inference, the image is expanded to multiples of eight. Does the model fail in this way?

Thank you for your interest in our work! In fact, it's quite common in image-to-image tasks to train on patches and then perform inference on the whole image. This approach can indeed work effectively.

**Comment by zhaozhaoooo** [comment]
Okay, I understand. Thank you very much for your answer!
