### ISSUE TITLE
how to train appearance task with Doc3DShade?

### ISSUE THREAD

**Issue by weinixuehao** [ZZZHANG-jx/DocRes#18]
![1-0_10-iliad_Page_034-Hg90001-L2_9_7-T_7500_6300-I_8871_7317](https://github.com/user-attachments/assets/ce88e01a-862c-4dd9-873a-c76304bf2716)
![4-0_-12 5-pp_Page_054-1yr0001-L2_2_8-T_18500_2200-I_8890_7101](https://github.com/user-attachments/assets/0f2c67db-361d-4105-90c3-14e1f878b004)
Do use the docaligner to flat doc before training?

**Comment by ZZZHANG-jx** [comment]
We have updated the [README](https://github.com/ZZZHANG-jx/DocRes/blob/cddd0b17a73ce2319687f0c59134fe8acf01e4c3/data/README.md#dataset-preparation) to provide clearer instructions for data preparation.
