### ISSUE TITLE
DTSPrompt

### ISSUE THREAD

**Issue by fengyanWang** [ZZZHANG-jx/DocRes#21]
非常感谢您开源这么棒的项目，请问如果我这边想让模型直接学习一批数据，输入是未美化，未去除手写的，输出图片是经过美化，轻微矫正和去除手写的，请问应该使用哪个任务比较合理？
输入图片
![image](https://github.com/user-attachments/assets/3d9f474b-7b9a-4cb6-98a6-f8d564d6b395)
输出图片：
![image](https://github.com/user-attachments/assets/6423dd31-877d-4d14-992f-524aca5dcf59)

**Comment by ZZZHANG-jx** [comment]
你好，按我的理解这里应该有3个子任务：dewarping, appearance enhancement (把文档变成干净的pdf样式), handwritten text erasure. 
1. 根据你提供的数据，直接训练应该是不行的，至少需要把dewarping任务和另外两个任务分离开来。即训练appearance enhancement和handwritten text erasure任务时应该保证输入和gt是空间位置上对齐的。
2. appearance enhancement和handwritten text erasure可以考虑当成一个任务训练，即输入是包含拍照阴影等噪声以及手写的图像，gt则是干净pdf样式并且手写去除后的图像（gt没有经过几何矫正）
3. appearance enhancement和handwritten text erasure当成两个任务的话需要构建两种gt（gt没有经过几何矫正）：干净pdf样式但手写未去除；非干净pdf样式但手写去除
4. 当加入新任务时，最简单的DTSPrompt可以直接采用一个常数矩阵

**Comment by fengyanWang** [comment]
> 你好，按我的理解这里应该有3个子任务：dewarping, appearance enhancement (把文档变成干净的pdf样式), handwritten text erasure.
> 
> 1. 根据你提供的数据，直接训练应该是不行的，至少需要把dewarping任务和另外两个任务分离开来。即训练appearance enhancement和handwritten text erasure任务时应该保证输入和gt是空间位置上对齐的。
> 2. appearance enhancement和handwritten text erasure可以考虑当成一个任务训练，即输入是包含拍照阴影等噪声以及手写的图像，gt则是干净pdf样式并且手写去除后的图像（gt没有经过几何矫正）
> 3. appearance enhancement和handwritten text erasure当成两个任务的话需要构建两种gt（gt没有经过几何矫正）：干净pdf样式但手写未去除；非干净pdf样式但手写去除
> 4. 当加入新任务时，最简单的DTSPrompt可以直接采用一个常数矩阵

非常感谢您的回复，请问handwritten text erasure任务中输入和输出图片空间位置不对齐应该使用哪种算法可以处理，因为对齐的数据比较难搞。

**Comment by fengyanWang** [comment]
> > > 你好，按我的理解这里应该有3个子任务：dewarping, appearance enhancement (把文档变成干净的pdf样式), handwritten text erasure.
> > > 
> > > 1. 根据你提供的数据，直接训练应该是不行的，至少需要把dewarping任务和另外两个任务分离开来。即训练appearance enhancement和handwritten text erasure任务时应该保证输入和gt是空间位置上对齐的。
> > > 2. appearance enhancement和handwritten text erasure可以考虑当成一个任务训练，即输入是包含拍照阴影等噪声以及手写的图像，gt则是干净pdf样式并且手写去除后的图像（gt没有经过几何矫正）
> > > 3. appearance enhancement和handwritten text erasure当成两个任务的话需要构建两种gt（gt没有经过几何矫正）：干净pdf样式但手写未去除；非干净pdf样式但手写去除
> > > 4. 当加入新任务时，最简单的DTSPrompt可以直接采用一个常数矩阵
> > 
> > 
> > 非常感谢您的回复，请问handwritten text erasure任务中输入和输出图片空间位置不对齐应该使用哪种算法可以处理，因为对齐的数据比较难搞。
> 
> 可以试我们另一个工作DocAligner ([code](https://github.com/ZZZHANG-jx/DocAligner), [arxiv](https://arxiv.org/abs/2306.05749))，这是首个用于文档图像对齐的工作，可以用于多种拍照文档图像任务的真实数据标注，目前前向代码已开源。

感谢感谢，我试试！

**Comment by ZZZHANG-jx** [comment]
> > > > 你好，按我的理解这里应该有3个子任务：dewarping, appearance enhancement (把文档变成干净的pdf样式), handwritten text erasure.
> > > > 
> > > > 1. 根据你提供的数据，直接训练应该是不行的，至少需要把dewarping任务和另外两个任务分离开来。即训练appearance enhancement和handwritten text erasure任务时应该保证输入和gt是空间位置上对齐的。
> > > > 2. appearance enhancement和handwritten text erasure可以考虑当成一个任务训练，即输入是包含拍照阴影等噪声以及手写的图像，gt则是干净pdf样式并且手写去除后的图像（gt没有经过几何矫正）
> > > > 3. appearance enhancement和handwritten text erasure当成两个任务的话需要构建两种gt（gt没有经过几何矫正）：干净pdf样式但手写未去除；非干净pdf样式但手写去除
> > > > 4. 当加入新任务时，最简单的DTSPrompt可以直接采用一个常数矩阵
> > > 
> > > 
> > > 非常感谢您的回复，请问handwritten text erasure任务中输入和输出图片空间位置不对齐应该使用哪种算法可以处理，因为对齐的数据比较难搞。
> > 
> > 
> > 可以试我们另一个工作DocAligner ([code](https://github.com/ZZZHANG-jx/DocAligner), [arxiv](https://arxiv.org/abs/2306.05749))，这是首个用于文档图像对齐的工作，可以用于多种拍照文档图像任务的真实数据标注，目前前向代码已开源。
> 
> 感谢感谢，我试试！

欢迎star我们的工作！

**Comment by fengyanWang** [comment]
> > > > > 你好，按我的理解这里应该有3个子任务：dewarping, appearance enhancement (把文档变成干净的pdf样式), handwritten text erasure.
> > > > > 
> > > > > 1. 根据你提供的数据，直接训练应该是不行的，至少需要把dewarping任务和另外两个任务分离开来。即训练appearance enhancement和handwritten text erasure任务时应该保证输入和gt是空间位置上对齐的。
> > > > > 2. appearance enhancement和handwritten text erasure可以考虑当成一个任务训练，即输入是包含拍照阴影等噪声以及手写的图像，gt则是干净pdf样式并且手写去除后的图像（gt没有经过几何矫正）
> > > > > 3. appearance enhancement和handwritten text erasure当成两个任务的话需要构建两种gt（gt没有经过几何矫正）：干净pdf样式但手写未去除；非干净pdf样式但手写去除
> > > > > 4. 当加入新任务时，最简单的DTSPrompt可以直接采用一个常数矩阵
> > > > 
> > > > 
> > > > 非常感谢您的回复，请问handwritten text erasure任务中输入和输出图片空间位置不对齐应该使用哪种算法可以处理，因为对齐的数据比较难搞。
> > > 
> > > 
> > > 可以试我们另一个工作DocAligner ([code](https://github.com/ZZZHANG-jx/DocAligner), [arxiv](https://arxiv.org/abs/2306.05749))，这是首个用于文档图像对齐的工作，可以用于多种拍照文档图像任务的真实数据标注，目前前向代码已开源。
> > 
> > 
> > 感谢感谢，我试试！
> 
> 欢迎star我们的工作！

必须滴！
