### ISSUE TITLE
About data preparation for doc3d

### ISSUE THREAD

**Issue by SijieLiu518** [ZZZHANG-jx/DocRes#23]
请教一下作者
mask 是如何提取出来的？
原数据集 doc3d 的 bm 文件夹的数据格式是xx.mat，在这里是直接转换 xx.npy 吗？
<img width="670" alt="截屏2024-12-24 下午1 32 45" src="https://github.com/user-attachments/assets/c6b14c9f-79e4-48b2-880c-bdea11d399e3" />

**Comment by ZZZHANG-jx** [comment]
> 请教一下作者 mask 是如何提取出来的？ 原数据集 doc3d 的 bm 文件夹的数据格式是xx.mat，在这里是直接转换 xx.npy 吗？ <img alt="截屏2024-12-24 下午1 32 45" width="670" src="https://private-user-images.githubusercontent.com/64841662/398328338-c6b14c9f-79e4-48b2-880c-bdea11d399e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMTkyODEsIm5iZiI6MTczNTAxODk4MSwicGF0aCI6Ii82NDg0MTY2Mi8zOTgzMjgzMzgtYzZiMTRjOWYtNzllNC00OGIyLTg4MGMtYmRlYTExZDM5OWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDA1NDMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMzM0OGJhZTE2MmI0OTNkZjYyMTY3YzFlYzRmNDcyNjkxMzA1ODQ3M2NlZjExNGM5ZmU4MTc3MTgwM2I3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.40ql46MmPoplEwx_Vf6JtVWGjWEgDn0Pm5yE5KcWCg4">

1、Doc3D数据集本身是有mask标注的，uv标注的其中一个通道就是mask信息，可以从那里面提取
2、npy格式文件是由mat格式文件转化来的（操作具体如下），这样做是因为之前有测试过好像np.load的方式速度会快点
```
fmap=h5.loadmat(path)['bm']
np.save(new_path, fmap)
```

**Comment by SijieLiu518** [comment]
感谢作者的解答！！！
