### ISSUE TITLE
Different Image Task Input Issues

### ISSUE THREAD

**Issue by lxy5513** [ZZZHANG-jx/DocRes#7]
@ZZZHANG-jx  I highly appreciate the your work on document restoration based on prompts, and the ideas in it are extremely beneficial. Thank for your aworsome job.

In the paper, I am a bit confused about the dewarping task. The input image for this task includes some padding outside the document, whereas for other tasks, the input is the document itself. Is this design specific to the characteristics of the dewarping task? Why is it done this way?

Why we input this(with some padding)
![image](https://github.com/ZZZHANG-jx/DocRes/assets/39720528/45e68d22-41ca-401b-a127-242c57a16628)
rather than 
![image](https://github.com/ZZZHANG-jx/DocRes/assets/39720528/a36b53fe-f8d7-437a-b2c0-dec32321edad)

**Comment by ZZZHANG-jx** [comment]
Thank you for your interest in our work. 

The current dewarping task primarily focuses on data that includes the surrounding environmental margins (i.e., the padding you mentioned). This is consistent with the data used in major dewarping benchmarks such as DocUNet, DIR300, and WarpDoc (the visual results in our paper were derived from the DIR300 dataset). We follow these previous works and also primarily consider cases with environmental margins.

There are also some works that address more diverse environmental margins, such as [Marior](https://arxiv.org/abs/2207.11515) and [DocTr++](https://ieeexplore.ieee.org/abstract/document/10374269/?casa_token=kbRxKDShvX0AAAAA:Eyko9L7jX5tTB5rhrpRwXHQ5GqhD3ISSPkqjMGP4zOs2q2nxhlC1VYYCxJbLpVY3q7ggsGMK86I8rmY). You might find it helpful to refer to the corresponding papers for these methods.

**Comment by lxy5513** [comment]
@ZZZHANG-jx I get it, Thanks for your kind reply
